# Generated by Django 4.2.1 on 2023-05-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.JSONField()),
                ('end_date', models.JSONField()),
                ('program', models.JSONField()),
                ('institution', models.JSONField()),
                ('city', models.JSONField()),
                ('country', models.JSONField()),
                ('comment', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.JSONField()),
                ('end_date', models.JSONField()),
                ('position', models.JSONField()),
                ('organisation', models.JSONField()),
                ('city', models.JSONField()),
                ('country', models.JSONField()),
                ('comment', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=64)),
                ('name', models.JSONField()),
                ('comment', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField()),
                ('type', models.CharField(choices=[('language', 'Language'), ('personal', 'Personal'), ('programming', 'Programming')], max_length=32)),
                ('comment', models.JSONField()),
            ],
        ),
    ]
