# Generated by Django 4.2.1 on 2023-05-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[('personal', 'Personal'), ('language', 'Language'), ('programming', 'Programming')], max_length=32),
        ),
    ]
